/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo.ewarung;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SaharasuP
 */
public class App extends javax.swing.JFrame {

    //DEKLARASI VARIABEL
    private String user = "user";
    private ArrayList<String> product = new ArrayList<>();
    private ArrayList<String> price = new ArrayList<>();

    //END DEKLARASI VARIABEL
    //METHOD TAMBAH PRODUK
    public void addProduk() {
        product.add("Coca-Cola");
        price.add("7000");
        product.add("Milkita");
        price.add("1000");
        product.add("Oreo");
        price.add("4000");
        product.add("Chiki");
        price.add("1000");
        product.add("Mie Kremez");
        price.add("1000");
        product.add("Biskuat");
        price.add("2000");
        product.add("Kratingdaeng");
        price.add("9000");
        product.add("Kopikap");
        price.add("500");
        product.add("NU Green Tea");
        price.add("6000");
        product.add("Bear Brand");
        price.add("8000");

        DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
        ArrayList<String> data = new ArrayList<>();
        for (int i = 0; i < product.size(); i++) {
            data.add(product.get(i));
            data.add(price.get(i));
            model.addRow(data.toArray());
            data.clear();
        }
    }

    //END METHOD TAMBAH PRODUK
    private void pesanProduk() {
        DefaultTableModel produk = (DefaultTableModel) tabelProduk.getModel();
        DefaultTableModel keranjang = (DefaultTableModel) tabelKeranjang.getModel();
        int row = tabelProduk.getSelectedRow();
        ArrayList<String> data = new ArrayList<>();
        String qty = "";
        String input;

        String nmproduk = produk.getValueAt(row, 0).toString();
        String hrg = produk.getValueAt(row, 1).toString();
        do {
            input = JOptionPane.showInputDialog("Jumlah yang akan dibeli");
            if (input.matches("^[0-9]*$")) {
                qty = input;
            } else {
                JOptionPane.showMessageDialog(this, "Harap hanya input angka!");
            }
        } while (!input.matches("^[0-9]*$"));

        int harga = Integer.parseInt(hrg) * Integer.parseInt(qty);
        hrg = Integer.toString(harga);

        data.add(nmproduk);
        data.add(qty);
        data.add(hrg);

        keranjang.addRow(data.toArray());
        textTotalHarga.setText(totalHarga());
    }
    
    private void hapusKeranjang() {
        int opsi = JOptionPane.showConfirmDialog(null, "Ingin mengosongkan keranjang?");
        switch (opsi) {
            case JOptionPane.YES_OPTION:
                DefaultTableModel model = (DefaultTableModel) tabelKeranjang.getModel();
                model.setRowCount(0);
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
        textTotalHarga.setText(totalHarga());
    }
    
    private void hapusItemKeranjang() {
        DefaultTableModel model = (DefaultTableModel) tabelKeranjang.getModel();
        int getSelectedRowForDeletion = tabelKeranjang.getSelectedRow();

        if (getSelectedRowForDeletion >= 0) {
            model.removeRow(getSelectedRowForDeletion);
            JOptionPane.showMessageDialog(null, "Pesanan dihapus dari keranjang");
        } else {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan.");
        }
        textTotalHarga.setText(totalHarga());
    }
    
    private String totalHarga() {
        String result = "";
        int keranjangRow = tabelKeranjang.getRowCount();

        int temp = 0;
        int valueInt;
        for (int i = 0; i < keranjangRow; i++) {
            String value = tabelKeranjang.getValueAt(i, 2).toString();
            valueInt = Integer.parseInt(value);

            temp += valueInt;
        }

        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);

        result = kursIndonesia.format(temp);
        return result;
    }

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appMainPanel = new javax.swing.JPanel();
        panelTeksWelcome = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        tabProduct = new javax.swing.JTabbedPane();
        tabAllProduct = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnPesan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        paneladdProduk = new javax.swing.JPanel();
        btnAddProduk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        apprightPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        btnBayar = new javax.swing.JButton();
        btnHapusKeranjang = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        textTotalHarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnHapusItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("K10's e-Warung");

        panelTeksWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelUser.setText("Hai "+user+"!");

        labelWelcome.setBackground(new java.awt.Color(204, 255, 153));
        labelWelcome.setText("Selamat datang di K10's e-Warung! Selamat berbelanja!");

        javax.swing.GroupLayout panelTeksWelcomeLayout = new javax.swing.GroupLayout(panelTeksWelcome);
        panelTeksWelcome.setLayout(panelTeksWelcomeLayout);
        panelTeksWelcomeLayout.setHorizontalGroup(
            panelTeksWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeksWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTeksWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTeksWelcomeLayout.createSequentialGroup()
                        .addComponent(labelUser)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTeksWelcomeLayout.setVerticalGroup(
            panelTeksWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeksWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Coca-Cola","7000"},
                {"Milkita","1000"},
                {"Oreo","4000"},
                {"Chiki","1000"},
                {"Mie Kremez","1000"},
                {"Biskuat","2000"},
                {"Kratingdaeng","9000"},
                {"Kopikap","500"},
                {"NU Green Tea","6000"},
                {"Bear Brand","8000"}
            },
            new String [] {
                "Nama", "Harga"
            })
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            }
        );
        tabelProduk.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelProduk);
        if (tabelProduk.getColumnModel().getColumnCount() > 0) {
            tabelProduk.getColumnModel().getColumn(0).setResizable(false);
        }

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>Klik tombol di bawah untuk memesan barang yang dipilih.</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesan)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabAllProductLayout = new javax.swing.GroupLayout(tabAllProduct);
        tabAllProduct.setLayout(tabAllProductLayout);
        tabAllProductLayout.setHorizontalGroup(
            tabAllProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAllProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabAllProductLayout.setVerticalGroup(
            tabAllProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAllProductLayout.createSequentialGroup()
                .addGroup(tabAllProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(tabAllProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabProduct.addTab("Semua Produk", tabAllProduct);

        btnAddProduk.setText("Tambah Produk");
        btnAddProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdukActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama");

        jLabel4.setText("Harga");

        txtProduk.setToolTipText("Masukkan nama produk disini");

        txtHarga.setToolTipText("Masukkan harga produk disini");
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout paneladdProdukLayout = new javax.swing.GroupLayout(paneladdProduk);
        paneladdProduk.setLayout(paneladdProdukLayout);
        paneladdProdukLayout.setHorizontalGroup(
            paneladdProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdProdukLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneladdProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneladdProdukLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddProduk)
                    .addGroup(paneladdProdukLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneladdProdukLayout.setVerticalGroup(
            paneladdProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdProdukLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(paneladdProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(paneladdProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAddProduk))
        );

        tabProduct.addTab("Tambah Produk", paneladdProduk);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout apprightPanelLayout = new javax.swing.GroupLayout(apprightPanel);
        apprightPanel.setLayout(apprightPanelLayout);
        apprightPanelLayout.setHorizontalGroup(
            apprightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        apprightPanelLayout.setVerticalGroup(
            apprightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apprightPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Produk", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKeranjang.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelKeranjang);

        btnBayar.setText("Bayar Sekarang");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnHapusKeranjang.setText("Kosongkan Keranjang");
        btnHapusKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKeranjangActionPerformed(evt);
            }
        });

        labelTotal.setText("Total");

        textTotalHarga.setEditable(false);
        textTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalHargaActionPerformed(evt);
            }
        });

        jLabel1.setText("Keranjang Anda");

        btnHapusItem.setText("Hapus dari Keranjang");
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appMainPanelLayout = new javax.swing.GroupLayout(appMainPanel);
        appMainPanel.setLayout(appMainPanelLayout);
        appMainPanelLayout.setHorizontalGroup(
            appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTeksWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appMainPanelLayout.createSequentialGroup()
                        .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(appMainPanelLayout.createSequentialGroup()
                                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHapusKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHapusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(appMainPanelLayout.createSequentialGroup()
                                        .addComponent(labelTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181)))
                .addComponent(apprightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        appMainPanelLayout.setVerticalGroup(
            appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apprightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(appMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTeksWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appMainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(textTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(appMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(btnHapusKeranjang)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Total harga belanja\n"+
                textTotalHarga.getText());
        hapusKeranjang();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnHapusKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKeranjangActionPerformed
        // TODO add your handling code here:
        hapusKeranjang();
    }//GEN-LAST:event_btnHapusKeranjangActionPerformed


    private void textTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalHargaActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        pesanProduk();
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if (tabelProduk.getRowCount() == 0) {
            addProduk();
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
        // TODO add your handling code here:
        hapusItemKeranjang();
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnAddProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdukActionPerformed
        // TODO add your handling code here:
        DefaultTableModel list = (DefaultTableModel) tabelProduk.getModel();
        ArrayList<String> produk = new ArrayList<>();

        if (txtProduk.getText().equals("")||txtHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap input nama produk dan harga!");
        } else {
            produk.add(txtProduk.getText());
            produk.add(txtHarga.getText());
            list.addRow(produk.toArray());
        }
    }//GEN-LAST:event_btnAddProdukActionPerformed

    private void txtHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyPressed
        // TODO add your handling code here:
        String value = txtHarga.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtHarga.setEditable(true);
        } else {
            txtHarga.setEditable(false);
            JOptionPane.showMessageDialog(this, "Harap input harga dengan angka!");
        }
    }//GEN-LAST:event_txtHargaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appMainPanel;
    private javax.swing.JPanel apprightPanel;
    private javax.swing.JButton btnAddProduk;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnHapusKeranjang;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel panelTeksWelcome;
    private javax.swing.JPanel paneladdProduk;
    private javax.swing.JPanel tabAllProduct;
    private javax.swing.JTabbedPane tabProduct;
    private javax.swing.JTable tabelKeranjang;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField textTotalHarga;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtProduk;
    // End of variables declaration//GEN-END:variables
}
